###########################################################################################
#   tomcat配置修改
###########################################################################################
server:
  # 端口号
  port: 80
  servlet:
    session:
      # session最大超时时间
      timeout: 60
  tomcat:
    uri-encoding: utf-8

mybatis:
  mapper-locations: classpath:mapping/*.xml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/scfdataworks?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      stat-view-servlet:
        allow: true
  # 热部署
  devtools:
    restart:
      enabled: true
      additional-paths: src/main
      additional-exclude: WEB-INF/**
  # freemarker 静态资源配置
  freemarker:
    # 设定ftl文件路径
    template-loader-path: classpath:/templates
    # 关闭缓存，即时刷新，生产环境需要改成TRUE
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
  # thymeleaf静态资源配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false

#分页
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql