@startuml
'https://plantuml.com/sequence-diagram

autonumber

note over 调拨中心
end note
调拨中心 -> 协同履约: 1:po单下发履约
协同履约 -> 协同履约: 2:创建采购履约单
协同履约 -> 协同履约: 3:创建采购入库通知单
协同履约 -> 实物履约: 4:生成一张入库单
调拨中心 -> 调拨中心: 5:创建ASN单据
调拨中心 -> 调拨中心: 6:发货指令下发
调拨中心 -> 实物履约:7:创建送货单MQ
实物履约 -> 实物履约: 8:拆合送货单
实物履约 -> WMS: 9:下发入库通知单
WMS --> 实物履约: 10:同步wms部分入库消息
实物履约 --> 协同履约: 10.1.1:更新采购单履约状态=部分入库，更新sku已经出库数量
协同履约 --> 调拨中心: 10.1.2:发送采购入库消息
调拨中心 -> 调拨中心: 10.1.3:采购单入库处理
WMS --> 实物履约: 10.2.1:同步wms确认入库消息
实物履约 --> 协同履约: 10.2.2:更新采购单履约状态=全部入库，更新sku确认出库数量
协同履约 -> 调拨中心: 10.2.3:发送确认入库消息给调拨中心
调拨中心 -> 调拨中心: 10.2.4:采购单全部入库处理
调拨中心 -> 调拨中心: 10.2.5:采购单完成
调拨中心 -> 协同履约: 10.2.6:采购履约单完成
@enduml